import "./globals.css";
import Header from "../../componentes/header/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="antialiased">
        <Header/>
        <main className="p-6">
          {children}
        </main>
      </body>
    </html>
  );
}
